name: Montezuma Club
favicon: null
layout_spectrum: 1
typography_spectrum: 0.001135938335210085
title: Montezuma Club
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5eaf0'
    - '#1d1815'
    - '#b5c2cb'
    - '#466021'
    - '#8b8579'
  brandStrength: 0.7299080376978964
  lightness: 0.5392955031711608
  saturation: 0.674931569956243
  rhythmicContrast: 0.08700586040504277
purpose: []
