name: Montezuma Club
favicon: null
layout_spectrum: 1
typography_spectrum: 0.14347
title: Montezuma Club
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5eaf0'
    - '#1d1815'
    - '#b5c2cb'
    - '#466021'
    - '#8b8579'
  brandStrength: 0.125
  lightness: 0.875
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
