typography_spectrum: 0.25060100574046373
color:
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
  brandStrength: 0.46345926471985877
  lightness: 0.16621017805300653
  saturation: 0.690618313383311
  rhythmicContrast: 0.7943769183475524
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8503201405983418
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Lucas M. Ormi
  email: lucas.oromi@gmail.com
name: Montezuma Club
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: 3D Models
    id: 5ac7813c-cec3-4108-88e7-be33497f602d
    type: content
  - name: Location
    id: f4148a81-6bb5-4638-b350-1f530a4a3ed3
    type: content
  - name: Fauna
    id: ebb07047-da41-4194-8be5-a2eaed3bcaab
    type: content
  - name: Pets
    id: 4788580c-529a-41b3-978a-b46682e57b6e
    type: content
  - name: Flora
    id: 7badd5a7-9f90-4aa9-9927-a647ab9473c3
    type: content
  - name: Places
    id: f33a0779-349b-41bf-a199-8fd1e9e5a24f
    type: content
favicon: null
title: Montezuma Club
purpose:
  - type: external
    url: 'https://s3-us-west-2.amazonaws.com/vrevit/win64/GameMA73D.zip'
    label: Downlaoad 3D Game
